### ISSUE TITLE
Don't hardcode cursor size

### ISSUE THREAD

**Issue by Cogitri** [Cogitri/gxi#106]
I suppose we could make it proportional to the editor font

**Comment by LiHRaM** [comment]
After digging a little into `EditView.rs`, I discovered that changing the rectangle size to fit the dimensions of `self.interface_font`, it would match the font.
![image](https://user-images.githubusercontent.com/25297553/53451482-258e7100-3a1f-11e9-8ae2-b8a85c5650ec.png)
It was my intuition, however, that the interface font should just be used for menus, etc, and that the editor font should be used for the editor. This might suggest a flaw in the UI logic somewhere.

```diff
diff --git a/src/edit_view.rs b/src/edit_view.rs
index 55ced73..2788a28 100644
--- a/src/edit_view.rs
+++ b/src/edit_view.rs
@@ -718,11 +718,9 @@ impl EditView {
                     // Draw the cursor
                     cr.rectangle(
                         (f64::from(x)) - hadj.get_value(),
-                        (((self.edit_font.font_ascent + self.edit_font.font_descent) as u64) * i)
-                            as f64
-                            - vadj.get_value(),
+                        self.interface_font.font_height * i as f64 - vadj.get_value(),
                         CURSOR_WIDTH,
-                        self.edit_font.font_ascent + self.edit_font.font_descent,
+                        self.interface_font.font_height,
                     );
                     cr.fill();
                 }
```

**Comment by Cogitri** [comment]
> This might suggest a flaw in the UI logic somewhere.

Ah, since the editor font's height is that of the entire line the cursor looks rather big. I guess it's only a coincidence that the cursor looks OK if you use the interface font to decide on how big the cursor should be, if the fonts don't have the same height this happens:

![screenshot from 2019-02-27 15-12-36](https://user-images.githubusercontent.com/8766773/53496359-33390a80-3aa2-11e9-990b-4e9a538a61ec.png)

Not quite sure what's the problem with the current cursor height. It doesn't seem so big to me, it's just as big as the line.

**Comment by LiHRaM** [comment]
My issue with the cursor height is that it doesn't scale with the font. It seems that both interface_font and edit_font are completely detached from whatever font_height the font is actually being set to. :confused:

**Comment by Cogitri** [comment]
Ooohhh, I guess we don't recalculate everything but the font name in EVFont and EVInterfaceFont and only do that when initializing the EditView! You could test this: Make the font larger and then open a new EditView. Is the cursor size correct now?

**Comment by LiHRaM** [comment]
I tried that, didn't work.
Did some more digging around, and it seems like the `edit_font` is initialized as Inconsolata 16, and then the rest of the metrics are calculated from that, along with the language which is also set as an arbitrary default. https://github.com/Cogitri/gxi/blob/master/src/edit_view.rs#L145-L170

Then, in `config_changed`, we only calculate the `font_desc` property of the `edit_font`, (for `size` and `font_face` respectively) where in reality we should also derive the rest of the struct fields from the font description. (This should be easy enough, the `edit_view` contains a reference to the drawing area, which gives us access to the pango context, which allows us to derive all sorts of black magic.

**Comment by Cogitri** [comment]
Yes, as I said, we have to recalculate EVFont and EVInterfaceFont fields on config_changed

**Comment by Cogitri** [comment]
FWIW, right now the EditView hardcodes Inconsolata 16 as initial font because EditView doesn't get a Config passed to its new() function and Xi sends us config_changed with the actual font anyway. Would be cleaner to get the right font from the start though

**Comment by LiHRaM** [comment]
> Would be cleaner to get the right font from the start though

Agreed.
