### ISSUE TITLE
Adding a statusbar

### ISSUE THREAD

**Issue by Cogitri** [Cogitri/gxi#111]
We could add a statusbar to gxi to make the headerbar less crowded, it could look a little like this:

![screenshot from 2019-02-27 17-13-44](https://user-images.githubusercontent.com/8766773/53504876-148f3f80-3ab3-11e9-8fe6-9c92c3906d35.png)

**Comment by LiHRaM** [comment]
Sounds good, I also think xi-editor supports a status bar

**Comment by Cogitri** [comment]
Oh my, thanks for the heads up!

**Comment by LiHRaM** [comment]
I'm pretty new to GTK, what kind of widget would you suggest for a statusbar?

**Comment by Cogitri** [comment]
Ah [Statusbar](https://gtk-rs.org/docs/gtk/struct.Statusbar.html) seems fitting :)

**Comment by Cogitri** [comment]
Also, I can highly recommend you to run gxi or similar apps (e.g. Gedit) with `--gtk-debug=all`, that shows you neatly how the widgets and containers are used

**Comment by LiHRaM** [comment]
Hmmm. I looked for a Statusbar widget in Glade earlier, but seems it was missing. (See https://gitlab.gnome.org/GNOME/glade/issues/302.) I guess I'll just have to use the workaround mentioned in there. :p

I'll have a look at running it with that flag.

**Comment by Cogitri** [comment]
Yup. Maybe do that in its own file though, since we're (most likely?) going to add the Statusbar to the EditView

**Comment by Cogitri** [comment]
fixed in 75f8debb51ed670a40caac25dc7db759ce68c8c4
