### ISSUE TITLE
Scrolling with mouse wheel sometimes stops working

### ISSUE THREAD

**Issue by jansol** [Cogitri/gxi#175]
Not sure what's going on, seems somewhat related to the WM forcing the window size (snap to top-right quarter of screen etc). This seems to also break resizing the window but I'm not sure as the GTK window has practically nonexistent borders that can be grabbed with the mouse in order to resize the window. If dragging in the window shadow should resize it, that is not possible when focus-follows-mouse is enabled, as focus switches to the window below before one can start the grab gesture.

**Comment by Cogitri** [comment]
Mind starting gxi in a terminal and providing a log with `env RUST_LOG=trace gxi`? That'd help me greatly to understand what's going on.

**Comment by jansol** [comment]
Hmmmmmmm and of course I can't repro it anymore. I did get a panic on exit though, but the stacktrace is just `<unknown>` due to it being a release build...
