### ISSUE TITLE
[Bug] Wrong cursor position.

### ISSUE THREAD

**Issue by PsiACE** [Cogitri/gxi#187]
![gxi-error-wrong-cursor-position](https://user-images.githubusercontent.com/36896360/55944128-7ded9b00-5c7a-11e9-8874-c35fd6a984b3.png)

Built from the main branch, no major updates be ignored.

The wrong cursor position. Accumulated as the number of line feeds increases, eventually deviating.

Also, consider not letting the linecount and line spacing be so cramped.

**Comment by Cogitri** [comment]
> Built from the main branch, no major updates be ignored

I don't encounter that here, what font do you use?

> Also, consider not letting the linecount and line spacing be so cramped.

That should be better with bigger fonts, but I'll try to improve it for smaller fonts soon (am in holidays right now, so it'll take me a week or so :)

**Comment by PsiACE** [comment]
> I don't encounter that here, what font do you use?

Monospace Regular. In fact, not only that, I also repeated the problem when I tried to use other fonts. Not sure exactly why, is there any way to help me expose more information? 

OS: Fedora 29 [All up to date]
Kernel: x86_64 Linux 5.0.6-200.fc29.x86_64

> That should be better with bigger fonts

You're right. It's also a good idea to consider resizing linecount fonts. These thoughts stem from some comparisons, and please forgive me for being picky in these places.

**Comment by PsiACE** [comment]
Maybe I'll have some time to try this, but don't be hopeful.

**Comment by Cogitri** [comment]
Alright, I'm currently on holidays without my laptop on me, so I won't be able to work on this before next weekend :/

**Comment by Cogitri** [comment]
Mind sending me your $HOME/.config/gxi/preferences.xiconfig?

**Comment by PsiACE** [comment]
Sorry, I am not at the computer. Do you mind waiting for 90 minutes?

**Comment by Cogitri** [comment]
Sure, just do it when you have some free time :)

**Comment by PsiACE** [comment]
Sorry, I'm late.

```
tab_size = 4
translate_tabs_to_spaces = false
use_tab_stops = true
plugin_search_path = [""]
font_face = "Monospace"
font_size = 18
auto_indent = false
scroll_past_end = false
wrap_width = 0
word_wrap = false
autodetect_whitespace = true
line_ending = "\n"
surrounding_pairs = [["\"", "\""], ["'", "'"], ["{", "}"], ["[", "]"]]
save_with_newline = true
```

**Comment by Cogitri** [comment]
Thanks, will look into it in a bit.

**Comment by Cogitri** [comment]
Hun, I can't reproduce it with your config, the cursor works fine for me :/

Could you please also do `gsettings list-recursively com.github.Cogitri.gxi`

**Comment by Linger2** [comment]
I have the same bug in my Manjaro, whatever with any font or size or theme. 
By the way, my default locale setting as `LANG=zh_CN.UTF-8`, and I have some like-bug on other gtk application.

Linux

> 4.19.32-1-MANJARO

Config

```
tab_size = 4
translate_tabs_to_spaces = false
use_tab_stops = true
plugin_search_path = [""]
font_face = "DejaVu Sans"
font_size = 17
auto_indent = true
scroll_past_end = false
wrap_width = 0
word_wrap = false
autodetect_whitespace = true
line_ending = "\n"
surrounding_pairs = [["\"", "\""], ["'", "'"], ["{", "}"], ["[", "]"]]
```

Setting 
```
com.github.Cogitri.gxi theme-name 'Solarized (light)'
com.github.Cogitri.gxi draw-spaces false
com.github.Cogitri.gxi draw-tabs false
```

**Comment by Cogitri** [comment]
@Linger2 What version of gxi are you using?

**Comment by PsiACE** [comment]
Looks like it might have something to do with the locale setting? I think that's the right way to think about it.

**Comment by Cogitri** [comment]
Yes, that seems to be it, good combination! Will look into fixing it now :)

**Comment by Cogitri** [comment]
Sorry that it took me a bit, had some stuff to do that piled up during holidays. Mind trying #204? Somehow I can't seem to reproduce it anymore.

**Comment by PsiACE** [comment]
Thank you for your work. Due to some computer problems, I have not been working on Linux recently. I may not be able to test it well for the time being.
