### ISSUE TITLE
Tabs have non-symbolic close buttons and borders

### ISSUE THREAD

**Issue by bertob** [Cogitri/gxi#236]
The tabs are using non-symbolic icons for their close buttons, which looks a bit weird. The GNOME HIG recommends only using symbolic icons for buttons.

The close buttons also have button-style borders, which normal close buttons on tabs don't have.

![image](https://user-images.githubusercontent.com/1908896/57762868-8ebd8080-7700-11e9-80b4-cbbc3f0759ea.png)

Here's Gedit for comparison:

![image](https://user-images.githubusercontent.com/1908896/57762920-b01e6c80-7700-11e9-988c-890e4979854f.png)

**Comment by Cogitri** [comment]
Thanks for bringing this to my attention, will work on it after I' done with #233! :)
