### ISSUE TITLE
Overlay Scrollbars

### ISSUE THREAD

**Issue by bertob** [Cogitri/gxi#251]
The current scrollbars are static, which makes them very prominently visible and looks a bit unelegant. The GNOME HIG recommend using overlay scrollbars, which have all the functional characteristics of fixed scrollbars, but look less prominent. Most other GTK text editors use them, so I see no reason why they wouldn't work here, too :)

**Comment by Cogitri** [comment]
Ah, I guess a bit like a ScrolledWindow does? I did try switching to it for nicer Scrollbars (see #233), but for some reason the Scrollbar's upper would always reset when focussing out of gxi. I guess I'll revisit it after I'm done with #240, thanks for the issue! :)

**Comment by Cogitri** [comment]
Hm, I've tried it again in #253, but sadly the ScrolledWindow still bugs out when focusing out/allocating a new size :c

**Comment by Cogitri** [comment]
Thanks for opening, it should be fixed now and mainstreamed gxi's scrolling a lot! :)
