### ISSUE TITLE
Cannot Build

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [Cogitri/gxi#265]
## Error: no default toolchain configured
When I run `sudo ninja -C build install` I get the following output
```shell
ninja: Entering directory `build'
[0/3] Generating cargo-build-gxi with a custom command.
	GXI Plugindir: /usr/local/lib/gxi/plugins
	GXI Localedir:       /usr/local/share/locale
	GXI Version:         0.7.0
	Crossbuild:          false
	Detected GTK+3.22:   true

error: no default toolchain configured
FAILED: gxi
/home/doc/Downs/gxi/scripts/cargo.sh .. /home/doc/Downs/gxi/build/. gxi /home/doc/Downs/gxi/build gxi false true /usr/local/lib/gxi/plugins /usr/local/share/locale 0.7.0
ninja: build stopped: subcommand failed.
```

## System Information
<b>OS: </b>Void Linux
<b>Rust Version: </b>1.35

I am unsure of what no default toolchain could mean

**Comment by Cogitri** [comment]
I think your rustup isn't configured correctly, could you do the following and then try again?

`rustup default stable`

**Comment by Th3Whit3Wolf** [comment]
@Cogitri I tried but I get the same error

**Comment by Th3Whit3Wolf** [comment]
I don't know if this is relevant but this is my output from `ninja -C build`
```shell
ninja: Entering directory `build'
[0/2] Generating cargo-build-gxi with a custom command.
	GXI Plugindir: /usr/local/lib/gxi/plugins
	GXI Localedir:       /usr/local/share/locale
	GXI Version:         0.7.0
	Crossbuild:          false
	Detected GTK+3.22:   true

    Finished release [optimized] target(s) in 0.18s
[1/2] Generating cargo-build-syntect with a custom command.
	GXI Plugindir: /usr/local/lib/gxi/plugins
	GXI Localedir:       /usr/local/share/locale
	GXI Version:         0.7.0
	Crossbuild:          false
	Detected GTK+3.22:

    Finished release [optimized] target(s) in 0.09s
```

**Comment by Cogitri** [comment]
Hm, weird, the `no default toolchain configured` certainly is on rustup: https://stackoverflow.com/questions/44303915/no-default-toolchain-configured-after-installing-rustup

Also see https://github.com/tock/tock/issues/832 which is a similar problem.

**Comment by aclonegeek** [comment]
I also run into this issue every time I build. I've only been able to successfully build by running this command instead:
`sudo -E ninja -C build install`

**Comment by Cogitri** [comment]
Ah, so it's sudo resetting the environment, that sounds plausible. Could you send me the output of both: `sudo env` and `sudo -E env`?

**Comment by aclonegeek** [comment]
@Cogitri 

sudo env:
```
COLORTERM=truecolor
XAUTHORITY=/home/randy/.Xauthority
LANG=C
TERM=xterm-256color
DISPLAY=:0
PATH=/home/randy/.local/bin:/home/randy/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
MAIL=/var/mail/root
LOGNAME=root
USER=root
HOME=/root
SHELL=/bin/bash
SUDO_COMMAND=/usr/bin/env
SUDO_USER=randy
SUDO_UID=1000
SUDO_GID=985
```

sudo -E env:
```
SHELL=/bin/bash
WINDOWID=31457283
COLORTERM=truecolor
HISTSIZE=
DOTNET_CLI_TELEMETRY_OPTOUT=1
EDITOR=emacsclient -c
XDG_SEAT=seat0
PWD=/home/randy
LOGNAME=root
XDG_SESSION_TYPE=tty
XAUTHORITY=/home/randy/.Xauthority
DESKTOP_STARTUP_ID=i3/alacritty/584-23-archy_TIME32227311
TERMINAL=alacritty
WINDOWPATH=1
HOME=/home/randy
LANG=C
XDG_SESSION_CLASS=user
TERM=xterm-256color
USER=root
DISPLAY=:0
SHLVL=2
XDG_VTNR=1
XDG_SESSION_ID=1
XDG_RUNTIME_DIR=/run/user/1000
BROWSER=firefox-nightly
PATH=/home/randy/.local/bin:/home/randy/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
ALACRITTY_LOG=/tmp/Alacritty-16919.log
HISTFILESIZE=
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
MAIL=/var/spool/mail/randy
_=/usr/bin/sudo
SUDO_COMMAND=/usr/bin/env
SUDO_USER=randy
SUDO_UID=1000
SUDO_GID=985
```

I haven't built for awhile, but I do remember having an issue authenticating via polkit (I don't remember what it is, though). I'll have to try again sometime and see.

**Comment by Cogitri** [comment]
I think the `HOME` is the offender because rustup looks for the toolchains in $HOME/.cargo/bin. Could you try with `sudo env HOME=/home/<your user> ninja -C build`?

**Comment by Cogitri** [comment]
#279 works around this by making sure cargo is only ever invoked during building, which should always be done with an unprivileged user (and as such without sudo).
