### ISSUE TITLE
Adjust cursor size when font size is different from the default

### ISSUE THREAD

**Issue by Cogitri** [Cogitri/gxi#9]

**Comment by aclonegeek** [comment]
This seems to work for me - the cursor matches the font's size.

**Comment by Cogitri** [comment]
When I filed a issue it did until a certain point - especially very small fonts (<8) trigger this (but that's really not that much of a problem, I guess). Thanks for testing :)

**Comment by Cogitri** [comment]
Seems to work now (so I guess it has been fixed somewhere along the way). Thanks for noticing!
